is_static: true
pretrained_model_path: ./checkpoints/CompVis/stable-diffusion-v1-4
output_dir: outputs/coffee
train_data:
  video_path: data/coffee.mp4
  prompt: Coffee is pouring
  n_sample_frames: 4
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
  - Milk is pouring
  - Cream is pouring
  - Cookies are pouring
  - Soup is pouring
  video_length: 4
  width: 512
  height: 512
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 300
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
